# Generated by Django 3.0.7 on 2020-07-01 03:25

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AsyncResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(db_index=True, max_length=255, verbose_name='task id')),
                ('result', models.TextField(verbose_name='task result')),
                ('created_on', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, db_index=True, verbose_name='created_on')),
            ],
        ),
    ]
